<!doctype html><html lang=en-us><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Error Handling | PowerShell By Example</title><link rel=stylesheet href=/%20/css/style.css%20><link rel=stylesheet href=/%20/css/fonts.css%20><title>PowerShell By Example</title><meta name=description content="PowerShell by Example is a hands-on introduction to PowerShell using annotated example programs."><meta name=keywords content="powershell,progamming,tutorial"><link rel=alternate type=application/rss+xml href=https://powershellbyexample.dev/index.xml title=powershellbyexample.dev><link rel=icon type=image/png sizes=32x32 href=https://powershellbyexample.dev/icons/favicon-32x32.png><meta name=twitter:image:src content="https://raw.githubusercontent.com/sanderstad/powershellbyexample/main/static/twittercard.png"><meta name=twitter:site content="@sqlstad"><meta name=twitter:card content="summary_large_image"><meta name=twitter:title content="Learning PowerShell By Example"><meta name=twitter:description content="PowerShell by Example is a hands-on introduction to PowerShell using annotated example programs."><meta property="og:image" content="https://raw.githubusercontent.com/sanderstad/powershellbyexample/main/static/twittercard.png"><meta property="og:image:alt" content="PowerShell by Example"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="600"><meta property="og:site_name" content="PowerShell By Example"><meta property="og:type" content="object"><meta property="og:title" content="Learning PowerShell By Example"><meta property="og:url" content="https://powershellbyexample.dev"><meta property="og:description" content="PowerShell by Example is a hands-on introduction to PowerShell using annotated example programs."><script type=text/javascript>sdkInstance="appInsightsSDK",window[sdkInstance]="appInsights";var sdkInstance,aiName=window[sdkInstance],aisdk=window[aiName]||function(n){function t(t){e[t]=function(){var n=arguments;e.queue.push(function(){e[t].apply(e,n)})}}e={config:n},e.initialize=!0;var e,o=document,i=window,s,a,r;setTimeout(function(){var e=o.createElement("script");e.src=n.url||"https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js",o.getElementsByTagName("script")[0].parentNode.appendChild(e)});try{e.cookie=o.cookie}catch(e){}e.queue=[],e.version=2;for(s=["Event","PageView","Exception","Trace","DependencyData","Metric","PageViewPerformance"];s.length;)t("track"+s.pop());return t("startTrackPage"),t("stopTrackPage"),a="Track"+s[0],(t("start"+a),t("stop"+a),t("setAuthenticatedUserContext"),t("clearAuthenticatedUserContext"),t("flush"),!(!0===n.disableExceptionTracking||n.extensionConfig&&n.extensionConfig.ApplicationInsightsAnalytics&&!0===n.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking))&&(t("_"+(s="onerror")),r=i[s],i[s]=function(t,n,o,i,a){var c=r&&r(t,n,o,i,a);return!0!==c&&e["_"+s]({message:t,url:n,lineNumber:o,columnNumber:i,error:a}),c},n.autoExceptionInstrumented=!0),e}({instrumentationKey:"182786de-33f9-4d34-abc9-68ce85a717a0"});window[aiName]=aisdk,aisdk.queue&&0===aisdk.queue.length&&aisdk.trackPageView({})</script><script async src="https://www.googletagmanager.com/gtag/js?id=G-WRS58SRCQM"></script>
<script>var doNotTrack=!1;if(!doNotTrack){window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","G-WRS58SRCQM",{anonymize_ip:!1})}</script><script type=application/javascript>var doNotTrack=!1;doNotTrack||(window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","G-WRS58SRCQM","auto"),ga("send","pageview"))</script><script async src=https://www.google-analytics.com/analytics.js></script></head><body><nav><ul class=menu></ul><hr></nav><div class=article-meta><h1><span class=title><a href=https://powershellbyexample.dev/>PowerShell By Example</a>: Error Handling</span></h1></div><main><p>The try/catch blocks in PowerShell are used to handle terminating error. With the try/catch block you also have a finally keyword that will be executed even when an error is found.</p><h2 id=general>General</h2><p>The example below is a standard way to do a try/catch block</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-powershell data-lang=powershell><span style=display:flex><span><span style=color:#66d9ef>try</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># This will generate an error</span>
</span></span><span style=display:flex><span>    1/0
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;This is executed after the error&#34;</span>
</span></span><span style=display:flex><span>} <span style=color:#66d9ef>catch</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># Catch all errors</span>
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;Oh oh! Error occurred.</span><span style=color:#ae81ff>`n</span><span style=color:#e6db74>$_&#34;</span>
</span></span><span style=display:flex><span>}
</span></span></code></pre></div><p>Result:</p><pre tabindex=0><code>Oh oh! Error occurred.
Attempted to divide by zero.
</code></pre><p>You can see that an error was caught and that the error was returned as well.</p><h2 id=specific-error-catches>Specific error catches</h2><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-powershell data-lang=powershell><span style=display:flex><span><span style=color:#66d9ef>try</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># This will generate an error</span>
</span></span><span style=display:flex><span>    1/0
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;This is executed after the error&#34;</span>
</span></span><span style=display:flex><span>} <span style=color:#66d9ef>catch</span> <span style=color:#66d9ef>[System.DivideByZeroException]</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># Catch all errors</span>
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;Divide by zero error occurred.</span><span style=color:#ae81ff>`n</span><span style=color:#e6db74>$_&#34;</span>
</span></span><span style=display:flex><span>} <span style=color:#66d9ef>catch</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># Catch all errors</span>
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;Oh oh! Another error occurred.</span><span style=color:#ae81ff>`n</span><span style=color:#e6db74>$_&#34;</span>
</span></span><span style=display:flex><span>}
</span></span></code></pre></div><p>Result:</p><pre tabindex=0><code>Divide by zero error occurred.
Attempted to divide by zero.
</code></pre><p>As you can see the specific error is returned instead of the general catch.</p><h2 id=using-finally>Using finally</h2><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-powershell data-lang=powershell><span style=display:flex><span><span style=color:#66d9ef>try</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># This will generate an error</span>
</span></span><span style=display:flex><span>    1/0
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;This is executed after the error&#34;</span>
</span></span><span style=display:flex><span>} <span style=color:#66d9ef>catch</span> <span style=color:#66d9ef>[System.DivideByZeroException]</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># Catch all errors</span>
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;Divide by zero error occurred.</span><span style=color:#ae81ff>`n</span><span style=color:#e6db74>$_&#34;</span>
</span></span><span style=display:flex><span>} <span style=color:#66d9ef>catch</span> {
</span></span><span style=display:flex><span>    <span style=color:#75715e># Catch all errors</span>
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;Oh oh! Another error occurred.</span><span style=color:#ae81ff>`n</span><span style=color:#e6db74>$_&#34;</span>
</span></span><span style=display:flex><span>} <span style=color:#66d9ef>finally</span> {
</span></span><span style=display:flex><span>    Write-Host <span style=color:#e6db74>&#34;Finally!&#34;</span>
</span></span><span style=display:flex><span>}
</span></span></code></pre></div><p>Result:</p><pre tabindex=0><code>Divide by zero error occurred.
Attempted to divide by zero.
Finally!
</code></pre><p>As you can see the finally is always executed whether or not we have an error.</p></main><a class=previous href=/post/reading-files/>Next: Reading Files<footer><p><a href=https://powershellbyexample.dev/>Home</a></p><p>by <a href=https://sqlstad.nl target=_blank>Sander Stad</a> |
<a href=https://github.com/sanderstad/powershellbyexample target=_blank>source</a> |
<a href=https://github.com/sanderstad/powershellbyexample/blob/main/LICENSE target=_blank>license</a></p></footer></body></html>